### ISSUE TITLE
always you should run test in ram with sqlite  

### ISSUE THREAD

**Issue by JoDeveloper** [khatabwedaa/blog#9]
in database.php
'database' => env('DB_DATABASE', database_path('database.sqlite')),

in phpunit.xml : 
 
<env name="SESSION_DRIVER" value="array"/>
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>

**Comment by khatabwedaa** [comment]
thanks Joe :smile: :v:

**Comment by JoDeveloper** [comment]
> thanks Joe

I still  prefer it  :stuck_out_tongue_closed_eyes:
